DROP SEQUENCE IF EXISTS CLIENTE_SEQ;
CREATE SEQUENCE IF NOT EXISTS CLIENTE_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS cliente (
    id BIGINT DEFAULT NEXT VALUE FOR CLIENTE_SEQ PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL
);